<?xml version="1.0" encoding="utf-8"?><Database Name="QuanLi_Dormitory" Class="DbFeeConsumeDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=LAPTOP-1B55MD1L\SQLEXPRESS;Initial Catalog=QuanLi_Dormitory;Integrated Security=True" SettingsObjectName="Dormitory_Winform.Properties.Settings" SettingsPropertyName="QuanLi_DormitoryConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.vwFeeConsume" Member="vwFeeConsumes">
    <Type Name="vwFeeConsume">
      <Column Name="MaPhong" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TongPhiPhong" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
    </Type>
  </Table>
</Database>