#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dormitory_Winform
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QuanLi_Dormitory")]
	public partial class DbFeeConsumeDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public DbFeeConsumeDataContext() : 
				base(global::Dormitory_Winform.Properties.Settings.Default.QuanLi_DormitoryConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DbFeeConsumeDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DbFeeConsumeDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DbFeeConsumeDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DbFeeConsumeDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<vwFeeConsume> vwFeeConsumes
		{
			get
			{
				return this.GetTable<vwFeeConsume>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vwFeeConsume")]
	public partial class vwFeeConsume
	{
		
		private System.Nullable<int> _Nam;
		
		private System.Nullable<decimal> _TongPhi;
		
		public vwFeeConsume()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nam", DbType="Int")]
		public System.Nullable<int> Nam
		{
			get
			{
				return this._Nam;
			}
			set
			{
				if ((this._Nam != value))
				{
					this._Nam = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TongPhi", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> TongPhi
		{
			get
			{
				return this._TongPhi;
			}
			set
			{
				if ((this._TongPhi != value))
				{
					this._TongPhi = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
