<?xml version="1.0" encoding="utf-8"?><Database Name="QuanLi_Dormitory" Class="DbStudentPerYearDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=LAPTOP-1B55MD1L\SQLEXPRESS;Initial Catalog=QuanLi_Dormitory;Integrated Security=True" SettingsObjectName="Dormitory_Winform.Properties.Settings" SettingsPropertyName="QuanLi_DormitoryConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.vwStudentPerYear" Member="vwStudentPerYears">
    <Type Name="vwStudentPerYear">
      <Column Name="SoLuongSinhVien" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NamVao" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>