#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dormitory_Winform
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QuanLi_Dormitory")]
	public partial class DbStudentPerYearDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public DbStudentPerYearDataContext() : 
				base(global::Dormitory_Winform.Properties.Settings.Default.QuanLi_DormitoryConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DbStudentPerYearDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DbStudentPerYearDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DbStudentPerYearDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DbStudentPerYearDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<vwStudentPerYear> vwStudentPerYears
		{
			get
			{
				return this.GetTable<vwStudentPerYear>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vwStudentPerYear")]
	public partial class vwStudentPerYear
	{
		
		private System.Nullable<int> _SoLuongSinhVien;
		
		private System.Nullable<System.DateTime> _NamVao;
		
		public vwStudentPerYear()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuongSinhVien", DbType="Int")]
		public System.Nullable<int> SoLuongSinhVien
		{
			get
			{
				return this._SoLuongSinhVien;
			}
			set
			{
				if ((this._SoLuongSinhVien != value))
				{
					this._SoLuongSinhVien = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NamVao", DbType="Date")]
		public System.Nullable<System.DateTime> NamVao
		{
			get
			{
				return this._NamVao;
			}
			set
			{
				if ((this._NamVao != value))
				{
					this._NamVao = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
