//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dormitory_Winform
{
    using System;
    using System.Collections.Generic;
    
    public partial class NguoiThan
    {
        public int MaNT { get; set; }
        public int MaSV { get; set; }
        public string Ten { get; set; }
        public System.DateTime NgayTham { get; set; }
        public string DiaChi { get; set; }
        public string DienThoai { get; set; }
    
        public virtual SinhVien SinhVien { get; set; }
    }
}
