//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dormitory_Winform
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuanLi_DormitoryEntities : DbContext
    {
        public QuanLi_DormitoryEntities()
            : base("name=QuanLi_DormitoryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ADMIN> ADMINS { get; set; }
        public virtual DbSet<HAOPHI> HAOPHIs { get; set; }
        public virtual DbSet<KHOANPHI> KHOANPHIs { get; set; }
        public virtual DbSet<LOAIPHONGSVDKI> LOAIPHONGSVDKIs { get; set; }
        public virtual DbSet<NGUOITHAN> NGUOITHANs { get; set; }
        public virtual DbSet<PHONG> PHONGs { get; set; }
        public virtual DbSet<SINHVIEN> SINHVIENs { get; set; }
        public virtual DbSet<SINHVIENVAOPHONG> SINHVIENVAOPHONGs { get; set; }
        public virtual DbSet<THIETBI> THIETBIs { get; set; }
    }
}
