//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dormitory_Winform
{
    using System;
    using System.Collections.Generic;
    
    public partial class SINHVIENVAOPHONG
    {
        public int MaSVVaoPhong { get; set; }
        public int MaSV { get; set; }
        public string LoaiPhongSVDangKi { get; set; }
        public string MaPhong { get; set; }
        public System.DateTime NgayVao { get; set; }
    
        public virtual PHONG PHONG { get; set; }
    }
}
